### ISSUE TITLE
AudioContext should not be closed

### ISSUE THREAD

**Issue by alexthewilde** [elsmr/mp3-mediarecorder#121]
https://github.com/eliasmeire/mp3-mediarecorder/blob/c154ddcbf94f19cddd7187b5bfe993176cc34ae4/src/recorder/index.ts#L75

Closing the AudioContext here makes it impossible to re-use the context on subsequent recordings.

Removing this line fixes the issue.

**Comment by elsmr** [comment]
Hm I think I added this to limit the amount of open `AudioContext`s, if you don't pass in your own `AudioContext` (to fix #59). I shouldn't close it if you pass in your own `AudioContext`. I'll make a fix!
