### ISSUE TITLE
Race condition inside worker

### ISSUE THREAD

**Issue by kjaunslavietis** [elsmr/mp3-mediarecorder#125]
If an instance of the worker is created, attached to a MediaRecorder instance, and MediaRecorder.start() is called (following your example), there is a race condition where the worker will receive a START_RECORDING message and attempt to access the vmsg.wasm in `onStartRecording` which hasn't been loaded yet by `getWasmModule` . This will cause it to fail silently and the recorder will stay in 'inactive' state.

**Comment by elsmr** [comment]
Hey thanks for the report! I'll have a look at this soon

**Comment by elsmr** [comment]
Hi this issue should be fixed in `mp3-mediarecorder@4.0.3`. Can you verify? :smile:

**Comment by kjaunslavietis** [comment]
Looks good, thanks!

**Comment by fred-boink** [comment]
I think I am getting this issue on Nextjs not sure if I am loading the worker correctly, how do I debug this?
