### ISSUE TITLE
Terminating a worker

### ISSUE THREAD

**Issue by KeysonG** [elsmr/mp3-mediarecorder#148]
Hi! Thanks for the great lib, its awesome :)

How would I terminate a worker so they do not still show up in the Chrome Memory tab.

Thanks again!

**Comment by elsmr** [comment]
Hi :) Thanks for your kind words 

You could call `terminate` on the worker instance you pass to the `Mp3MediaRecorder` constructor. Keep in mind the recorder won't work anymore after terminating the worker (you'll have to create a new recorder with a new worker).

```ts
const recorder = new Mp3MediaRecorder(stream, { worker: myWorker });
myWorker.terminate()
```

Hope that solves your issue!

**Comment by KeysonG** [comment]
Thank you!
