### ISSUE TITLE
Cannot find config.type.ts

### ISSUE THREAD

**Issue by ansonmiu0214** [elsmr/mp3-mediarecorder#167]
mp3-mediarecorder version: 4.0.3

---

Error log when building Angular project which uses `mp3-mediarecorder`:

```
Error: node_modules/mp3-mediarecorder/worker/index.d.ts:1:33 - error TS2307: Cannot find module '../types/config.type' or its corresponding type declarations.

1 import { Mp3WorkerConfig } from '../types/config.type';
```

My package.json states that `mp3-mediarecorder` version 4.0.3 is being used. I see the `config.type.ts` file in this repo, but it is not present in my local `node_modules/mp3-mediarecorder` directory.

**Comment by elsmr** [comment]
HI there, sorry for the long wait, should be fixed in [`4.0.5`](https://github.com/elsmr/mp3-mediarecorder/releases/tag/v4.0.5) ! Cheers
