### ISSUE TITLE
Update event-target-shim as soon as they publish a fix for #26

### ISSUE THREAD

**Issue by Timebutt** [elsmr/mp3-mediarecorder#95]
We currently use `"event-target-shim": "github:cpmsmith/event-target-shim#sentry-infinite-recursion"` to quickly fix an issue when combining this library with the latest `@sentry/browser`.

As soon as [PR](https://github.com/mysticatea/event-target-shim/issues/26) is merged we should change that dependency to `event-target-shim` again.

**Comment by elsmr** [comment]
Fixed in #163
